http:
  middlewares:
    https-redirect:
      redirectScheme:
        scheme: https
        permanent: true

tls:
  certificatesResolvers:
    myresolver:
      acme:
        email: your-email@domain.com
        storage: /letsencrypt/acme.json
        httpChallenge:
          entryPoint: web
